package com.moppy.control.gui.netpanel;

import com.moppy.core.comms.bridge.BridgeSerial;
import com.moppy.core.comms.bridge.BridgeUDP;
import com.moppy.core.comms.bridge.MultiBridge;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sam
 */
public class NetworkSelectorPanel extends javax.swing.JPanel {

    private MultiBridge networkBridge;
    
    /**
     * Creates new form NetworkSelectorPanel
     */
    public NetworkSelectorPanel() {
        initComponents();
    }
    
    public void initNetworkPanel(MultiBridge networkBridge) {
        this.networkBridge = networkBridge;
        
        try {
            this.add(new NetPanelUDP(networkBridge, new BridgeUDP()));
        } catch (UnknownHostException ex) {
            Logger.getLogger(NetworkSelectorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        BridgeSerial.getAvailableSerials()
            .forEach(serial -> this.add(new NetPanelSerial(networkBridge, new BridgeSerial(serial))));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
