package com.moppy.control.gui;

import com.moppy.control.GUIControlledPostProcessor;
import com.moppy.control.MoppyPreferences;
import com.moppy.control.NetworkManager;
import com.moppy.core.events.mapper.MapperCollection;
import com.moppy.core.midi.MoppyMIDIReceiverSender;
import com.moppy.core.midi.MoppyMIDISequencer;
import com.moppy.core.status.StatusBus;
import javax.sound.midi.MidiMessage;

/**
 *
 */
public class MainWindow extends javax.swing.JFrame {

    private final StatusBus statusBus;
    private final MoppyMIDIReceiverSender receiverSender;
    private final MoppyMIDISequencer midiSequencer;
    private final NetworkManager netManager;
    private final MapperCollection<MidiMessage> mappers;
    private final GUIControlledPostProcessor postProc;


    /**
     * Creates new form MainWindow
     */
    public MainWindow(StatusBus statusBus, MoppyMIDIReceiverSender receiverSender, MoppyMIDISequencer midiSequencer, NetworkManager netManager, MapperCollection<MidiMessage> mappers, GUIControlledPostProcessor postProc) {
        this.statusBus = statusBus;
        this.receiverSender = receiverSender;
        this.midiSequencer = midiSequencer;
        this.netManager = netManager;
        this.mappers = mappers;
        this.postProc = postProc;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sequencerPanel = new com.moppy.control.gui.SequencerPanel();
        sequencerPanel.setReceiverSender(receiverSender);
        sequencerPanel.setMidiSequencer(midiSequencer);
        sequencerPanel.setPostProcessor(postProc);
        statusBus.registerConsumer(sequencerPanel);
        jScrollPane2 = new javax.swing.JScrollPane();
        mapperCollectionPanel = new com.moppy.control.gui.mapperpanel.MapperCollectionPanel();
        mapperCollectionPanel.initMapperCollectionPanel(mappers);
        statusBus.registerConsumer(mapperCollectionPanel);
        networkPanel = new com.moppy.control.gui.netpanel.NetworkPanel();
        networkPanel.setNetworkManager(netManager);
        statusBus.registerConsumer(networkPanel);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Moppy Control");
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setPreferredSize(MoppyPreferences.getConfiguration().getMainWindowSize());
        setSize(MoppyPreferences.getConfiguration().getMainWindowSize());
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        sequencerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setViewportView(mapperCollectionPanel);

        networkPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sequencerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(networkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sequencerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(networkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Save our mappers before closing
        mapperCollectionPanel.saveMappersToConfig();
    }//GEN-LAST:event_formWindowClosing

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        MoppyPreferences.getConfiguration().setMainWindowSize(this.getSize());
    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private com.moppy.control.gui.mapperpanel.MapperCollectionPanel mapperCollectionPanel;
    private com.moppy.control.gui.netpanel.NetworkPanel networkPanel;
    private com.moppy.control.gui.SequencerPanel sequencerPanel;
    // End of variables declaration//GEN-END:variables
}
